import { describe, expect, it, vi } from "vitest";
import { overdueRentRemindersHandler } from "./scheduled/overdueRentReminders";

function response() { const state = { code: 200, body: undefined as unknown, res: undefined as any }; state.res = { status: vi.fn((code: number) => { state.code = code; return state.res; }), json: vi.fn((body: unknown) => { state.body = body; return body; }) }; return { state, res: state.res }; }
function chain(result: unknown) { const value: any = {}; value.from = vi.fn(() => value); value.where = vi.fn(() => value); value.limit = vi.fn(() => Promise.resolve(result)); value.leftJoin = vi.fn(() => value); value.orderBy = vi.fn(() => Promise.resolve(result)); return value; }
function updateChain() { const value: any = {}; value.set = vi.fn(() => value); value.where = vi.fn(() => Promise.resolve(undefined)); return value; }

describe("overdueRentRemindersHandler", () => {
  it("cron olmayan isteği reddeder", async () => { const { state, res } = response(); await overdueRentRemindersHandler({} as any, res, { authenticate: vi.fn().mockResolvedValue({ isCron: false }), getDatabase: vi.fn(), sendOwner: vi.fn() }); expect(state.code).toBe(403); expect(state.body).toEqual({ error: "cron-only" }); });
  it("taskUid uyuşmadığında isteği reddeder", async () => { const { state, res } = response(); const db = { select: vi.fn(() => chain([{ status: "aktif", scheduleCronTaskUid: "task-real" }])) }; await overdueRentRemindersHandler({} as any, res, { authenticate: vi.fn().mockResolvedValue({ isCron: true, taskUid: "task-fake" }), getDatabase: vi.fn().mockResolvedValue(db), sendOwner: vi.fn() }); expect(state.code).toBe(403); expect(state.body).toEqual({ error: "unexpected-task" }); });
  it("duraklatılmış kuralı bildirim oluşturmadan atlar", async () => { const { state, res } = response(); const db = { select: vi.fn(() => chain([{ status: "pasif", scheduleCronTaskUid: "task-1" }])) }; await overdueRentRemindersHandler({} as any, res, { authenticate: vi.fn().mockResolvedValue({ isCron: true, taskUid: "task-1" }), getDatabase: vi.fn().mockResolvedValue(db), sendOwner: vi.fn() }); expect(state.body).toEqual({ ok: true, skipped: "paused" }); });
  it("gecikme bulunduğunda uygulama içi kayıt ve owner uyarısı oluşturur", async () => { const { state, res } = response(); const rule = { id: 3, userId: 11, status: "aktif", scheduleCronTaskUid: "task-1", lastNotificationAt: null }; const db: any = { select: vi.fn().mockReturnValueOnce(chain([rule])).mockReturnValueOnce(chain([{ tenantName: "Ayşe Demir", unitNumber: "A-03", remaining: 26000 }])), update: vi.fn(() => updateChain()), insert: vi.fn(() => ({ values: vi.fn(() => ({ onDuplicateKeyUpdate: vi.fn().mockResolvedValue(undefined) })) })) }; const sender = vi.fn().mockResolvedValue(true); await overdueRentRemindersHandler({} as any, res, { authenticate: vi.fn().mockResolvedValue({ isCron: true, taskUid: "task-1" }), getDatabase: vi.fn().mockResolvedValue(db), sendOwner: sender }); expect((state.body as any).inAppRecorded).toBe(true); expect(sender).toHaveBeenCalledOnce(); expect(db.insert).toHaveBeenCalledOnce(); });
});
